
# https://docs.docker.com/compose/install/linux/
# docker run --rm -it -p 4566:4566 -p 4510-4559:4510-4559 localstack/localstack
# docker run --cap-add=IPC_LOCK -d --name=dev-vault hashicorp/vault


# docker run -p 8080:8080 -p 50000:50000 --restart=on-failure -v jenkins_home:/var/jenkins_home jenkins/jenkins:lts-jdk17


services:
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - ./jenkins_home:/var/jenkins_home:rw


# volumes:
#   data: