
# https://docs.docker.com/compose/install/linux/
# docker run --rm -it -p 4566:4566 -p 4510-4559:4510-4559 localstack/localstack
# docker run --cap-add=IPC_LOCK -d --name=dev-vault hashicorp/vault


# docker run -p 8080:8080 -p 50000:50000 --restart=on-failure -v jenkins_home:/var/jenkins_home jenkins/jenkins:lts-jdk17


services:
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
    # chmnod 777
      - ./jenkins_home:/var/jenkins_home:rw
      
  vault:
    image: hashicorp/vault:1.18
    ports:
      - 8200:8200
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=myroot
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
    cap_add:
      - IPC_LOCK 

  localstack:
    image: localstack/localstack
    ports:
      - 127.0.0.1:4566:4566            # LocalStack Gateway
      - 127.0.0.1:4510-4559:4510-4559  # external services port range
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=${DEBUG:-0}
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"


# volumes:
#   data: