services:
  jenkins:
    # For your convenience, uncomment to use this image instead of building it
    # image: danielefrancisz/jenkins-python3.12-awscli:latest
    build:
      dockerfile: ./Dockerfile
      args:
        LOCALSTACK_URL: localhost:4566
        STAGING_URL: localhost:8080
    network_mode: host
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - ./jenkins_home:/var/jenkins_home:rw
    user: "${UID}:${GID}"
    
  vault:
    image: hashicorp/vault:1.18
    network_mode: bridge
    ports:
      - 8200:8200
    environment:
      # To-Do
      # Better to use service tokens and not expose them in VCS. 
      # This state is for
      # development purposes only
      - VAULT_DEV_ROOT_TOKEN_ID=myroot
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
    cap_add:
      - IPC_LOCK 

  vault-loader:
    image: alpine/curl
    network_mode: host
    depends_on:
      - vault
    volumes:
      - ./vault-loader.sh:/usr/local/bin/vault-loader.sh:rwx
    command: ["sh", "-c", "/usr/local/bin/vault-loader.sh"]


  localstack:
    image: localstack/localstack
    network_mode: bridge
    ports:
      - 127.0.0.1:4566:4566           
      - 127.0.0.1:4510-4559:4510-4559 
    environment:
      - DEBUG=${DEBUG:-0}
      - EXTENSION_AUTO_LOAD=localstack-extension-terraform-init
    volumes:
      - "./main.tf:/etc/localstack/init/ready.d/main.tf"
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
