pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                echo 'Building..'
            }
        }
        stage('Test') {
            parallel([
                hello: {
                    echo "hello"
                },
                world: {
                    echo "world"
                }
            ])
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}