name: hello-world
on: push
jobs:
  sample-job:
    runs-on: self-hosted
    steps:
      - name: Build
        run: echo "This builds!"
      - name: Test
        run: echo "This tests!"
      - name: Deploy
        run: echo "This deploys!"