name: hello-world
on: push
jobs:
  my-job:
    runs-on: self-hosted
    steps:
      - name: Build
        run: echo "Hello World!"
      - name: Test
        run: echo "Hello World!"
      - name: Deploy
        run: echo "Hello World!"